# Generated by Django 2.2.9 on 2021-03-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.EmailField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Electronics', 'Electronics'), ('Fruits', 'Fruits'), ('Detergents', 'Detergents'), ('Fashion', 'Fashion'), ('Shoes', 'Shoes'), ('Perfumes', 'Perfumes')], max_length=15),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Electronics', 'Electronics'), ('Fruits', 'Fruits'), ('Detergents', 'Detergents'), ('Fashion', 'Fashion'), ('Shoes', 'Shoes'), ('Perfumes', 'Perfumes')], default='Food', max_length=15),
        ),
    ]
